spring:
  application:
    name: employee-api
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888
  cloud:
    config:
      fail-fast: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/my_office
    username: merch
    password: merch
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat