spring:
  application:
    name: employee-api
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888
  cloud:
    config:
      fail-fast: true
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    consumer:
      group-id: employee-api
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


kafka:
  topics:
    equipments-topic:
      name: com.epam.equipments.topic
      partitions: 1
      replicationFactor: 1