spring:
  application:
    name: equipment-api
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888
  cloud:
    config:
      fail-fast: true

  data:
    mongodb:
      url: mongodb://merch:merch@localhost:27017/equipment

server:
  port: 8079