server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/my_office
    username: merch
    password: merch
    driverClassName: org.postgresql.Driver
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat